#include QMK_KEYBOARD_H
#include "keymap_finnish.h"


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */
 
 
#define RA(key) RALT(key)
 
 
 enum layers {
	_BASE,
	_LOWER,
	_RAISE, 
	_ADJUST
 };
 
enum custom_keycodes {
	GAME = SAFE_RANGE
};


static const HSV color_base = {128, 255, 128};
static const HSV color_lower = {212, 255, 128};
static const HSV color_raise = {44, 255, 128};
static const HSV color_arrows = {0, 255, 128};

static bool gaming_mode = false;

#define FADE_SPEED 10  // smaller = slower

// One per LED
static HSV led_hsv_buffer[RGB_MATRIX_LED_COUNT];


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[_BASE] = LAYOUT(
		KC_ESC,		KC_1,		KC_2,		KC_3, 		KC_4,		KC_5, 								KC_6,		KC_7,		KC_8,		KC_9,		KC_0,		KC_MINS, 
		KC_TAB,		KC_Q,		KC_W,		KC_E,		KC_R, 		KC_T, 								KC_Y,		KC_U,		KC_I,		KC_O,		KC_P,		KC_LBRC, 
		KC_LWIN,	KC_A,		KC_S,		KC_D, 		KC_F,		KC_G, 								KC_H,		KC_J,		KC_K,		KC_L,		KC_SCLN,	KC_QUOT, 
		KC_LSFT,	KC_Z,		KC_X,		KC_C, 		KC_V, 		KC_B,		KC_ENT,		KC_BSPC,	KC_N,		KC_M,		KC_COMM,	KC_DOT,		KC_SLSH,	KC_RSFT, 
														KC_LALT,	MO(_LOWER),	KC_LCTL, 	KC_SPC,		MO(_RAISE),	KC_RALT
	),
	[_LOWER] = LAYOUT(
		_______, 	_______, 	RA(KC_2),	RA(KC_3),	RA(KC_4),  	RA(KC_5), 							RA(KC_6), 	RA(KC_7),	RA(KC_8),	RA(KC_9),	RA(KC_0), 	RA(KC_MINS), 
		_______, 	_______,	_______,	_______, 	_______, 	_______, 							_______, 	KC_HOME, 	KC_UP, 		KC_END,	 	_______, 	FI_CIRC, 	
		_______, 	_______, 	_______,	_______,	_______, 	_______, 							_______, 	KC_LEFT, 	KC_DOWN, 	KC_RGHT,	_______, 	KC_BSLS, 	
		_______, 	KC_NUBS, 	_______, 	_______, 	_______, 	_______, 	_______, 	_______, 	_______, 	_______,	_______,	_______, 	_______,	_______,	
														_______, 	_______, 	_______, 	KC_DEL, 	_______, 	_______
	),
	[_RAISE] = LAYOUT(
		KC_F12, 	KC_F1, 		KC_F2, 		KC_F3, 		KC_F4, 		KC_F5, 								KC_F6, 		KC_F7, 		KC_F8, 		KC_F9, 		KC_F10, 	KC_F11, 
		_______, 	_______, 	_______, 	_______, 	_______, 	_______, 							_______, 	KC_HOME, 	KC_UP, 		KC_END, 	_______, 	_______, 
		_______, 	_______, 	_______, 	_______, 	_______, 	_______, 							_______, 	KC_LEFT, 	KC_DOWN, 	KC_RGHT, 	_______, 	_______, 
		_______, 	_______, 	_______, 	_______, 	_______, 	_______, 	_______, 	_______, 	_______, 	_______, 	_______, 	_______, 	_______, 	_______, 
														_______, 	_______, 	_______, 	_______, 	_______, 	_______
	),
	[_ADJUST] = LAYOUT(
		QK_BOOT, 	_______, 	_______, 	_______, 	_______, 	_______, 						 	_______, 	_______, 	_______, 	_______, 	_______, 	KC_VOLU,  
		_______, 	_______, 	_______, 	_______, 	_______, 	_______, 						 	_______, 	_______, 	_______, 	_______, 	_______, 	_______,  
		_______, 	_______, 	_______, 	_______, 	_______, 	GAME, 						 		_______, 	_______, 	_______, 	_______, 	_______, 	_______,
		_______, 	_______, 	_______, 	_______, 	_______, 	_______, 	_______, 	_______, 	_______, 	_______, 	_______, 	_______, 	KC_VOLD, 	_______, 
														_______, 	_______, 	_______, 	_______, 	_______, 	_______
	)
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)


void keyboard_post_init_user(void) {
    rgb_matrix_mode(RGB_MATRIX_SOLID_COLOR);
	rgb_matrix_sethsv(128, 255, 128);
}


layer_state_t layer_state_set_user(layer_state_t state) {
    return update_tri_layer_state(state, _LOWER, _RAISE, _ADJUST);
}


bool process_record_user(uint16_t keycode, keyrecord_t *record) {
	switch (keycode) {
		case GAME:
			if (record->event.pressed) {
				gaming_mode = !gaming_mode;
			}
			return false;
		case KC_LALT:
			if (gaming_mode) {
				if (record->event.pressed) {
					register_code(KC_SPC);
				} else {
					unregister_code(KC_SPC);
				}
				return false;
			}
			break;
		case KC_SPC:
			if (gaming_mode) {
				if (record->event.pressed) {
					register_code(KC_LALT);
				} else {
					unregister_code(KC_LALT);
				}
				return false;
			}
			break;
	}
	
	return true;
}


static void fade_to_hsv(uint8_t i, HSV target) {
    HSV *current = &led_hsv_buffer[i];

    int16_t dh = target.h - current->h;
    if (abs(dh) > 127) dh -= (dh > 0) ? 255 : -255;  // handle hue wraparound
    current->h += (abs(dh) < FADE_SPEED) ? dh : (dh > 0 ? FADE_SPEED : -FADE_SPEED);

    int16_t ds = target.s - current->s;
    current->s += (abs(ds) < FADE_SPEED) ? ds : (ds > 0 ? FADE_SPEED : -FADE_SPEED);

    int16_t dv = target.v - current->v;
    current->v += (abs(dv) < FADE_SPEED) ? dv : (dv > 0 ? FADE_SPEED : -FADE_SPEED);

    RGB rgb = hsv_to_rgb(*current);
    rgb_matrix_set_color(i, rgb.r, rgb.g, rgb.b);
}


bool is_numeric(uint16_t keycode) {
	switch (keycode) {
		case KC_0:
		case KC_1:
		case KC_2:
		case KC_3:
		case KC_4:
		case KC_5:
		case KC_6:
		case KC_7:
		case KC_8:
		case KC_9:
			return true;
		default:
			return false;
	}
}


bool rgb_matrix_indicators_user(void) {
    uint8_t layer = get_highest_layer(layer_state);

    for (uint8_t row = 0; row < MATRIX_ROWS; row++) {
        for (uint8_t col = 0; col < MATRIX_COLS; col++) {
            uint8_t index = g_led_config.matrix_co[row][col];
			
			if (index == NO_LED) {
				continue;
			}
			
            uint16_t keycode = keymaps[layer][row][col];
			uint16_t base_keycode = keymaps[_BASE][row][col];
			
			HSV target = color_base;

			if (base_keycode == MO(_LOWER)) {
				target = color_lower;
			} else if (base_keycode == MO(_RAISE)) {
				target = color_raise;
			} else if (keycode == KC_UP || keycode == KC_DOWN || keycode == KC_LEFT || keycode == KC_RIGHT) {
				target = color_arrows;
			} else if (layer != _BASE && is_numeric(keycode)) {
				target = color_arrows;
			} else if (keycode != KC_TRNS) {
                switch (layer) {
                    case _LOWER:				
						target = color_lower;
                        break;
                    case _RAISE:
						target = color_raise;
                        break;
					case _ADJUST:
						target = color_arrows;
						break;
                }
            }
			
			fade_to_hsv(index, target);
        }
    }

    return true;
}
 